In [1]:
import numpy as np

In [2]:
np_array_1 = np.array([1,2,3,4])

print(np_array_1)
print(type(np_array_1))

[1 2 3 4]
<class 'numpy.ndarray'>


In [5]:
np_array_2 = np.array([[1,2,3],[4,5,6]])
print(np_array_2)

[[1 2 3]
 [4 5 6]]


In [6]:
# array의 행의 수 출력
print(np_array_2.ndim)

# array의 크기 출력
print(np_array_2.shape)

2
(2, 3)


In [9]:
# 0행렬을 만드는 행렬은  Zeros(크기)

Zero_array = np.zeros((3,4))
Zero_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
# 1로 채워진 행렬 >> ones()

once_array = np.ones((3,4))
once_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
# full() >> 0과 1이 아닌 우너하느 숫자로 채워서 행렬을 만든다

full_array = np.full((2,2),3.)
full_array

array([[3., 3.],
       [3., 3.]])

In [16]:
# 단위행렬을 만드는 함수 >> eye(크기)
# 행과 렬의 단위가 같아야 하기 때문에 하나의 숫자만 입력, 정사각형 형태

eye_array = np.eye(5)
eye_array


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
# 임의의 값을 가지는 행렬 >> random.ramdom(크기)

random_array = np.random.random((4,2))
random_array


array([[0.01929449, 0.12820681],
       [0.26993953, 0.00964357],
       [0.90830091, 0.32387532],
       [0.44373802, 0.78129823]])

In [27]:
# arange() >> 순차적인 데이터를 만들 때 사용

arange_array = np.arange(10)
arange_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
arange_array_2 = np.arange(2,10,2)
arange_array_2

array([2, 4, 6, 8])

In [28]:
# 행렬의 구조를 변경하는 함수 >> reshape(크기)

reshape_array = arange_array.reshape((2,5))
reshape_array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [33]:
# 행렬의 연산
x = np.array([1,2,3])
y = np.array([4,5,6])


In [37]:
print(x+y)
print(x-y)
print(x/y)

[5 7 9]
[-3 -3 -3]
[0.25 0.4  0.5 ]


In [38]:
# 행렬의 덧셈 > x + y , np.add(x,y)
print(np.add(x,y))

# 행렬의 뺄셈 > x -y  , np.subtract(x,y)
# 행렬의 나눗셈은 > x/y np.divide(x,y)
# 행렬의 곱셈은 > x * y , np.multiply(x,y)

[5 7 9]


In [41]:
# 행렬의 곱셈은 > x @ y, np.dot(x,y)

x2 = np.array([[1,2],[3,4]])
y2 = np.array([[5,6],[7,8]])

print(x2 @ y2)
np.dot(x2,y2)

[[19 22]
 [43 50]]


array([[19, 22],
       [43, 50]])